### ISSUE TITLE
Duration of time unclear for cost and volume axis lable.

### ISSUE THREAD

**Issue by safiume** [carbonplan/reports#26]
The horizontal axis doesn't clearly explain the duration of time per unit for volume or cost.
For example, when one selects volume, the unit is 'Volume tCO₂' is that (metric) tonnes CO₂ per year, or American tons per year? And for cost, is it yearly cost?

**Comment by freeman-lab** [comment]
Thanks for the feedback! Opened PR #30 with a much needed figure caption that hopefully helps here, along with some other tweaks to the text.

**Comment by safiume** [comment]
Thanks! I see the new changes but now it doesn't pull up project entry in firefox or safari.

**Comment by freeman-lab** [comment]
Ah! That was a separate bug, should now be fixed (but let us know if not in a new issue).
